---
abstract: 'Debugging tool for Plack web applications'
author:
  - 'Stevan Little <stevan@cpan.org>'
build_requires:
  HTTP::Request::Common: '0'
  Path::Class: '0'
  Test::Fatal: '0'
  Test::More: '0.88'
  Test::Warn: '0'
  UUID::Tiny: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
  File::ShareDir::Install: '0.06'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Plack-Debugger
requires:
  Config: '0'
  File::ShareDir: '0'
  File::Spec: '0'
  HTTP::Status: '0'
  JSON::XS: '0'
  Module::Versions: '0'
  POSIX: '0'
  Plack: '0'
  Scalar::Util: '0'
  Time::HiRes: '0'
  Try::Tiny: '0'
resources:
  repository: https://github.com/stevan/p5-plack-debugger.git
version: '0.02'
